tags:
  - name: Auth
paths:
  /signup:
    post:
      tags:
        - Auth
      summary: Signup user
      operationId: signupUser
      requestBody:
        description: Signup user object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUser"
      responses:
        "201":
          description: Success Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Bad Request
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User using this email already exists"
  /signin:
    post:
      tags:
        - Auth
      summary: Sigin user into the system
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: john.doe@example.com
                password:
                  type: string
                  example: "password"
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                  email:
                    type: string
                  name:
                    type: string
        "400":
          description: Incorrect email or password
  /logout:
    post:
      tags:
        - Auth
      summary: Logs out current logged in user session
      description: ""
      operationId: logoutUser
      parameters: []
      responses:
        default:
          description: successful operation
